### ISSUE TITLE
In Application Class repository.findById(1L) method is undefined

### ISSUE THREAD

**Issue by pasudo123** [spring-guides/gs-accessing-data-jpa#35]
Hi
(I am not good at English before I ask you a question.)

I'm practicing this project. (https://spring.io/guides/gs/accessing-data-jpa/)
but i try to this project, I'm in trouble.

```java
repository.findById(1L)
.ifPresent(customer -> {
        log.info("Customer found with findById(1L):");
	log.info("--------------------------------");
	log.info(customer.toString());
	log.info("");
});
```
my problem is
repository.findById(1L) method is undefined

how to solve this problem??

**Comment by gregturn** [comment]
This appears to be what happens when you use Spring Boot 2 with an older version of Spring Data. Spring Data used to have `findOne` which was replaced with `findById` as of Spring Boot 2.

If you have somehow forked the repo back in the Spring Boot 1.5 days, or overrode the guide's current settings of Boot 2 with Boot 1.5, then you would hit such a breaking change.

Also, `findById` returns an `Optional` while `findOne` would return a `null` if item not found.

**Comment by pasudo123** [comment]
Thank you. Thanks to you.
I was using the 1.5 version of Springboot.
